version: "3.8"
services:
  mysqldb:
    image: mysql:5.7.30
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=helloWorld
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
       - mysqldb


