INSERT INTO hello (word, lang) VALUES ('Zdravo svijete', 'Serbian');
INSERT INTO hello (word, lang) VALUES ('Hello World', 'English');
INSERT INTO hello (word, lang) VALUES ('Ciao Mondo', 'Italian');
INSERT INTO hello (word, lang) VALUES ('Olá Mundo', 'Portuguese');
INSERT INTO hello (word, lang) VALUES ('你好世界', 'Chinese');
INSERT INTO hello (word, lang) VALUES ('Hola Mundo', 'Spanish');
INSERT INTO hello (word, lang) VALUES ('Hej världen', 'Swedish');
INSERT INTO hello (word, lang) VALUES ('Salve mundi', 'Latin');
INSERT INTO hello (word, lang) VALUES ('Selam Dünya', 'Turkish');
INSERT INTO hello (word, lang) VALUES ('Hallo Welt', 'German');