INSERT INTO hello (word, lang) VALUES ('Zdravo svijete', 'sr');
INSERT INTO hello (word, lang) VALUES ('Hello World', 'en');
INSERT INTO hello (word, lang) VALUES ('Ciao Mondo', 'it');
INSERT INTO hello (word, lang) VALUES ('Olá Mundo', 'pt');
INSERT INTO hello (word, lang) VALUES ('你好世界', 'zh');
INSERT INTO hello (word, lang) VALUES ('Hola Mundo', 'es');
INSERT INTO hello (word, lang) VALUES ('Hej världen', 'sv');
INSERT INTO hello (word, lang) VALUES ('Salve mundi', 'la');
INSERT INTO hello (word, lang) VALUES ('Selam Dünya', 'tr');
INSERT INTO hello (word, lang) VALUES ('Hallo Welt', 'de');